import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

const resources = {
  en: {
    translation: {
      dashboard: 'Dashboard', users: 'Users', performance: 'Performance List', academy: 'Academy Members', referees: 'Referee Members', reports: 'Reports', logs: 'System Logs', settings: 'Settings', search: 'Search...', language: 'Language', theme: 'Theme', logout: 'Logout', totalUsers: 'Total Users', activeUsers: 'Active Users', totalReports: 'Total Reports', avgPerformance: 'Avg Performance', game: 'Game', region: 'Region', status: 'Status', role: 'Role', actions: 'Actions', edit: 'Edit', save: 'Save', cancel: 'Cancel', add: 'Add', delete: 'Delete', active: 'Active', passive: 'Passive', deactivationReason: 'Deactivation Reason', required: 'Required', participationTotal: 'Participation Total', overallPerformance: 'Overall Performance', testDet: 'Test Details', refDet: 'Ref. Details', notes: 'Notes',
      performanceManagement: 'Performance Management', performanceReports: 'Performance Reports',
      userId: 'Member ID', inGameUsername: 'In-Game Username', systemUsername: 'System Username', fullName: 'Full Name', roleCompetency: 'Role / Competency', academyRole: 'Academy Role', refereeRole: 'Referee Role', description: 'Description', testPart: 'Test Part.', bugReports: 'Bug Reports', suggestions: 'Suggestions', support: 'Support', refPerf: 'Ref. Perf.', refEveryone: 'Everyone/OTS', refSabotage: 'Sabotage', qa: 'QA', discordPc: 'Discord PC', mgrOpinion: 'Mgr. Opinion', member: 'Member', usersByGame: 'Users by Game', usersByRegion: 'Users by Region', topPerformers: 'Top Performers', systemActivity: 'System Activity', recentActivity: 'Recent Activity', roleSimulation: 'Role Simulation', profileSettings: 'Profile Settings', email: 'Email', noUsersFound: 'No users found for this game and region.', noAcademyFound: 'No academy members found for this game and region.', noRefereesFound: 'No referees found for this game and region.', notifications: 'Notifications', noNotifications: 'No new notifications', changeRoleDesc: 'Change your current role to simulate how the system looks for different users.', recentActionsDesc: 'Recent actions performed in the system.', userPerformanceUpdated: 'User performance updated', hoursAgo: 'hours ago by Admin', adminUser: 'Admin User', allGames: 'All Games', allRegions: 'All Regions', editUser: 'Edit User', copyToClipboard: 'Copy to clipboard', allRoles: 'All Roles', allStatuses: 'All Statuses',
      systemAccess: 'Create System Login', yes: 'Yes', no: 'No', resetPassword: 'Reset Password', passwordResetSuccess: 'Password reset request sent. User will set a new password on next login.', userLogs: 'User Logs', noLogs: 'No logs found.', roleManagement: 'Role Management', addNewRole: 'Add New Role', roleName: 'Role Name', permissions: 'Permissions', pages: 'Pages', deactivationReasonRequired: 'Please enter a reason for deactivating the user.', addUser: 'New User', userIdExists: 'This Member ID is already in use.', inGameUsernameExists: 'This In-Game Username is already in use.', systemUsernameExists: 'This System Username is already in use.', emailExists: 'This Email address is already in use.', invalidEmailFormat: 'Please enter a valid Email address.', invalidInGameUsernameFormat: 'In-Game Username must be 3-12 characters and can only contain letters, numbers, and allowed special characters: ! ^ / + ? = _ - $ # { } [ ] | ~ ` < > *', invalidSystemUsernameFormat: 'System Username must be 4-10 characters long and can only contain English letters and numbers.', discordIdExists: 'This Discord ID is already in use.', invalidDiscordIdFormat: 'Discord ID must be at least 17 digits.', discordIdRequired: 'Discord ID is required for Discord Moderators.',
      role_sysadmin: 'System Administrator', role_compmgr: 'Company Manager', role_compstaff: 'Company Staff', role_acadcap: 'Academy Captain', role_acadmem: 'Academy Member', role_fedaimem: 'Fedai Member', role_headref: 'Head Referee', role_ref: 'Referee', role_obs: 'Observer', role_discordmod: 'Discord Moderator', discordId: 'Discord ID', appTitle: 'MadByte Academy', footer_contact: 'Contact', discordTimeout: 'Discord Timeout', discordBan: 'Discord Ban', discordMessageDelete: 'Discord Msg Delete',
      month_01: 'JANUARY', month_02: 'FEBRUARY', month_03: 'MARCH', month_04: 'APRIL', month_05: 'MAY', month_06: 'JUNE', month_07: 'JULY', month_08: 'AUGUST', month_09: 'SEPTEMBER', month_10: 'OCTOBER', month_11: 'NOVEMBER', month_12: 'DECEMBER',
      yearly: 'Yearly', copySuccess: 'Copied to clipboard!',
      loginDesc: 'Performance Management Panel Login', usernameOrEmail: 'Username / Email', enterUsername: 'Enter username or email', noAccountDesc: 'If you don\'t have an account or have access issues', systemAdmin: 'System Administrator', contactWith: 'contact with.',
    }
  },
  tr: {
    translation: {
      dashboard: 'Panel', users: 'Kullanıcılar', performance: 'Performans Listesi', academy: 'Akademi Üyeleri', referees: 'Hakem Üyeleri', reports: 'Raporlar', logs: 'Sistem Kayıtları', settings: 'Ayarlar', search: 'Ara...', language: 'Dil', theme: 'Tema', logout: 'Çıkış', totalUsers: 'Toplam Kullanıcı', activeUsers: 'Aktif Kullanıcı', totalReports: 'Toplam Rapor', avgPerformance: 'Ort. Performans', game: 'Oyun', region: 'Bölge', status: 'Durum', role: 'Rol', actions: 'İşlemler', edit: 'Düzenle', save: 'Kaydet', cancel: 'İptal', add: 'Ekle', delete: 'Sil', active: 'Aktif', passive: 'Pasif', deactivationReason: 'Pasife Alma Nedeni', required: 'Zorunlu', participationTotal: 'Toplam Katılım', overallPerformance: 'Genel Performans', testDet: 'Test Detay', refDet: 'Hakem Detay', notes: 'Notlar',
      performanceManagement: 'Performans Yönetimi', performanceReports: 'Performans Raporları',
      userId: 'Kullanıcı Kimliği', inGameUsername: 'Oyun İçi Kullanıcı Adı', systemUsername: 'Sistem Kullanıcı Adı', fullName: 'Ad Soyad', roleCompetency: 'Rol / Yetkinlik', academyRole: 'Akademi Rolü', refereeRole: 'Hakem Rolü', description: 'Açıklama', testPart: 'Test Katılımı', bugReports: 'Hata Raporları', suggestions: 'Öneriler', support: 'Destek', refPerf: 'Hakem Perf.', refEveryone: 'Herkes Tek / ÖTS', refSabotage: 'Sabotaj', qa: 'QA', discordPc: 'Discord PC', mgrOpinion: 'Yönetici Görüşü', member: 'Üye', usersByGame: 'Oyuna Göre Kullanıcılar', usersByRegion: 'Bölgeye Göre Kullanıcılar', topPerformers: 'En İyi Performans Gösterenler', systemActivity: 'Sistem Aktivitesi', recentActivity: 'Son Aktiviteler', roleSimulation: 'Rol Simülasyonu', profileSettings: 'Profil Ayarları', email: 'E-Posta', noUsersFound: 'Bu oyun ve bölge için kullanıcı bulunamadı.', noAcademyFound: 'Bu oyun ve bölge için akademi üyesi bulunamadı.', noRefereesFound: 'Bu oyun ve bölge için hakem bulunamadı.', notifications: 'Bildirimler', noNotifications: 'Yeni bildirim yok', changeRoleDesc: 'Sistemin farklı kullanıcılar için nasıl göründüğünü simüle etmek için mevcut rolünüzü değiştirin.', recentActionsDesc: 'Sistemde gerçekleştirilen son eylemler.', userPerformanceUpdated: 'Kullanıcı performansı güncellendi', hoursAgo: 'saat önce Admin tarafından', adminUser: 'Admin Kullanıcı', allGames: 'Tüm Oyunlar', allRegions: 'Tüm Bölgeler', editUser: 'Kullanıcıyı Düzenle', copyToClipboard: 'Panoya kopyala', allRoles: 'Rol / Yetkinlik', allStatuses: 'Durum',
      systemAccess: 'Sistem Girişi Oluştur', yes: 'Evet', no: 'Hayır', resetPassword: 'Şifreyi Sıfırla', passwordResetSuccess: 'Şifre sıfırlama isteği gönderildi. Kullanıcı ilk girişinde yeni şifre belirleyecek.', userLogs: 'Kullanıcı Kayıtları', noLogs: 'Kayıt bulunamadı.', roleManagement: 'Rol Yönetimi', addNewRole: 'Yeni Rol Ekle', roleName: 'Rol Adı', permissions: 'Yetkiler', pages: 'Sayfalar', deactivationReasonRequired: 'Lütfen kullanıcıyı pasife çekme sebebini giriniz.', addUser: 'Kullanıcı Ekle', userIdExists: 'Bu Üye Kimliği zaten kullanılıyor.', inGameUsernameExists: 'Bu Oyun İçi Kullanıcı Adı zaten kullanılıyor.', systemUsernameExists: 'Bu Sistem Kullanıcı Adı zaten kullanılıyor.', emailExists: 'Bu E-Posta adresi zaten kullanılıyor.', invalidEmailFormat: 'Geçerli bir E-Posta adresi giriniz.', invalidInGameUsernameFormat: 'Oyun İçi Kullanıcı Adı 3-12 karakter uzunluğunda olmalı ve sadece harf, rakam ve izin verilen özel karakterleri içerebilir: ! ^ / + ? = _ - $ # { } [ ] | ~ ` < > *', invalidSystemUsernameFormat: 'Sistem Kullanıcı Adı 4-10 karakter uzunluğunda olmalı ve sadece İngilizce harf ve rakam içerebilir.', discordIdExists: 'Bu Discord ID zaten başka bir kullanıcıda kayıtlı.', invalidDiscordIdFormat: 'Discord ID sadece rakamlardan oluşmalı ve en az 17 haneli olmalıdır.', discordIdRequired: 'Discord Moderatörü rolü seçilen kullanıcılar için Discord ID girilmesi zorunludur.',
      role_sysadmin: 'Sistem Yöneticisi', role_compmgr: 'Şirket Yöneticisi', role_compstaff: 'Şirket Personeli', role_acadcap: 'Akademi Kaptanı', role_acadmem: 'Akademi Üyesi', role_fedaimem: 'Fedai Üyesi', role_headref: 'Baş Hakem', role_ref: 'Hakem', role_obs: 'Gözetmen', role_discordmod: 'Discord Moderatörü', discordId: 'Discord ID', appTitle: 'MadByte Akademi', footer_contact: 'İLETİŞİM', discordTimeout: 'Discord Uzaklaştırma', discordBan: 'Discord Yasaklama', discordMessageDelete: 'Discord Mesaj Silme',
      month_01: 'OCAK', month_02: 'ŞUBAT', month_03: 'MART', month_04: 'NİSAN', month_05: 'MAYIS', month_06: 'HAZİRAN', month_07: 'TEMMUZ', month_08: 'AĞUSTOS', month_09: 'EYLÜL', month_10: 'EKİM', month_11: 'KASIM', month_12: 'ARALIK',
      yearly: 'Yıllık', copySuccess: 'Panoya kopyalandı!',
      loginDesc: 'Performans Yönetim Paneli Girişi', usernameOrEmail: 'Kullanıcı Adı / E-Posta', enterUsername: 'Kullanıcı adı veya e-posta girin', noAccountDesc: 'Hesabınız yoksa veya erişim sorunu yaşıyorsanız', systemAdmin: 'Sistem Yöneticisi', contactWith: 'ile iletişime geçin.',
    }
  },
  az: {
    translation: {
      dashboard: 'Panel', users: 'İstifadəçilər', performance: 'Performans İdarəetməsi', academy: 'Akademiya Üzvləri', referees: 'Hakim Üzvləri', reports: 'Hesabatlar', logs: 'Sistem Qeydləri', settings: 'Tənzimləmələr', search: 'Axtar...', language: 'Dil', theme: 'Mövzu', logout: 'Çıxış', totalUsers: 'Ümumi İstifadəçi', activeUsers: 'Aktiv İstifadəçi', totalReports: 'Ümumi Hesabat', avgPerformance: 'Ort. Performans', game: 'Oyun', region: 'Bölgə', status: 'Status', role: 'Rol', actions: 'Əməliyyatlar', edit: 'Düzəliş et', save: 'Yadda saxla', cancel: 'Ləğv et', add: 'Əlavə et', delete: 'Sil', active: 'Aktiv', passive: 'Passiv', deactivationReason: 'Deaktivasiya Səbəbi', required: 'Məcburi', participationTotal: 'Ümumi İştirak', overallPerformance: 'Ümumi Performans', details: 'Detallar', notes: 'Qeydlər',
      performanceManagement: 'Performans İdarəetməsi', performanceReports: 'Performans Hesabatları',
      userId: 'Üzv ID', inGameUsername: 'Oyun İçi İstifadəçi Adı', systemUsername: 'Sistem İstifadəçi Adı', fullName: 'Ad Soyad', roleCompetency: 'Rol / Səriştə', academyRole: 'Akademiya Rolu', refereeRole: 'Hakim Rolu', description: 'Açıqlama', testPart: 'Test İştirakı', bugReports: 'Xəta Hesabatları', suggestions: 'Təkliflər', support: 'Dəstək', refPerf: 'Hakim Perf.', qa: 'QA', discordPc: 'Discord PC', mgrOpinion: 'Rəhbər Rəyi', member: 'Üzv', usersByGame: 'Oyuna Görə İstifadəçilər', usersByRegion: 'Bölgəyə Görə İstifadəçilər', topPerformers: 'Ən Yaxşı Performans Göstərənlər', systemActivity: 'Sistem Aktivliyi', recentActivity: 'Son Aktivliklər', roleSimulation: 'Rol Simulyasiyası', profileSettings: 'Profil Tənzimləmələri', email: 'E-poçt', noUsersFound: 'Bu oyun və bölgə üçün istifadəçi tapılmadı.', noAcademyFound: 'Bu oyun və bölgə üçün akademiya üzvü tapılmadı.', noRefereesFound: 'Bu oyun və bölgə üçün hakim tapılmadı.', notifications: 'Bildirişler', noNotifications: 'Yeni bildiriş yoxdur', changeRoleDesc: 'Sistemin fərqli istifadəçilər üçün necə göründüyünü simulyasiya etmək üçün mövcud rolunuzu dəyişdirin.', recentActionsDesc: 'Sistemdə həyata keçirilən son hərəkətlər.', userPerformanceUpdated: 'İstifadəçi performansı yeniləndi', hoursAgo: 'saat əvvəl Admin tərəfindən', adminUser: 'Admin İstifadəçi', allGames: 'Bütün Oyunlar', allRegions: 'Bütün Bölgələr', editUser: 'İstifadəçini Redaktə et', copyToClipboard: 'Mübadilə buferinə kopyala',
      systemAccess: 'Sistem Girişi Yarat', yes: 'Bəli', no: 'Xeyr', resetPassword: 'Şifrəni Sıfırla', passwordResetSuccess: 'Şifrə sıfırlama tələbi göndərildi.', userLogs: 'İstifadəçi Qeydləri', noLogs: 'Qeyd tapılmadı.', roleManagement: 'Rol İdarəetməsi', addNewRole: 'Yeni Rol Əlavə et', roleName: 'Rol Adı', permissions: 'İcazələr', pages: 'Səhifələr', deactivationReasonRequired: 'Zəhmət olmasa istifadəçini passivləşdirmə səbəbini daxil edin.', addUser: 'İstifadəçi Əlavə et', userIdExists: 'Bu Üzv ID-si artıq istifadədədir.', inGameUsernameExists: 'Bu Oyun İçi İstifadəçi Adı artıq istifadədədir.', systemUsernameExists: 'Bu Sistem İstifadəçi Adı artıq istifadədədir.', emailExists: 'Bu E-poçt ünvanı artıq istifadədədir.', invalidEmailFormat: 'Zəhmət olmasa keçərli E-poçt ünvanı daxil edin.', invalidInGameUsernameFormat: 'Oyun İçi İstifadəçi Adı 3-12 simvol olmalı və yalnız hərf, rəqəm və icazə verilən xüsusi simvolları ehtiva edə bilər: ! ^ / + ? = _ - $ # { } [ ] | ~ ` < > *', invalidSystemUsernameFormat: 'Sistem İstifadəçi Adı 4-10 simvol olmalıdır və yalnız İngilis hərfləri və rəqəmləri ehtiva edə bilər.', discordIdExists: 'Bu Discord ID artıq istifadədədir.', invalidDiscordIdFormat: 'Discord ID ən azı 17 rəqəmdən ibarət olmalıdır.', discordIdRequired: 'Discord ID tələb olunur.',
      role_sysadmin: 'Sistem Administratoru', role_compmgr: 'Şirket Meneceri', role_compstaff: 'Şirket İşçisi', role_acadcap: 'Akademiya Kapitanı', role_acadmem: 'Akademiya Üzvü', role_fedaimem: 'Fədai Üzvü', role_headref: 'Baş Hakim', role_ref: 'Hakim', role_obs: 'Müşahidəçi', role_discordmod: 'Discord Moderatoru', discordId: 'Discord ID', appTitle: 'MadByte Akademiya', footer_contact: 'Əlaqə', discordTimeout: 'Discord Uzaqlaşdırma', discordBan: 'Discord Qadağası', discordMessageDelete: 'Discord Mesaj Silmə',
      month_01: 'YANVAR', month_02: 'FEVRAL', month_03: 'MART', month_04: 'APREL', month_05: 'MAY', month_06: 'İYUN', month_07: 'İYUL', month_08: 'AVQUST', month_09: 'SENTYABR', month_10: 'OKTYABR', month_11: 'NOYABR', month_12: 'DEKABR',
      loginDesc: 'Performans İdarəetmə Paneli Girişi', usernameOrEmail: 'İstifadəçi Adı / E-poçt', enterUsername: 'İstifadəçi adı və ya e-poçt daxil edin', noAccountDesc: 'Hesabınız yoxdursa və ya giriş probleminiz varsa', systemAdmin: 'Sistem Administratoru', contactWith: 'ilə əlaqə saxlayın.',
    }
  },
  pt: {
    translation: {
      dashboard: 'Painel', users: 'Usuários', performance: 'Gestão de Desempenho', academy: 'Membros da Academia', referees: 'Membros Árbitros', reports: 'Relatórios', logs: 'Registros do Sistema', settings: 'Configurações', search: 'Pesquisar...', language: 'Idioma', theme: 'Tema', logout: 'Sair', totalUsers: 'Total de Usuários', activeUsers: 'Usuários Ativos', totalReports: 'Total de Relatórios', avgPerformance: 'Desempenho Médio', game: 'Jogo', region: 'Região', status: 'Status', role: 'Função', actions: 'Ações', edit: 'Editar', save: 'Salvar', cancel: 'Cancelar', add: 'Adicionar', delete: 'Excluir', active: 'Ativo', passive: 'Passivo', deactivationReason: 'Motivo da Desativação', required: 'Obrigatório', participationTotal: 'Participação Total', overallPerformance: 'Desempenho Geral', details: 'Detalhes', notes: 'Notas',
      performanceManagement: 'Gestão de Desempenho', performanceReports: 'Relatórios de Desempenho',
      userId: 'ID de Membro', inGameUsername: 'Nome no Jogo', systemUsername: 'Nome no Sistema', fullName: 'Nome Completo', roleCompetency: 'Função / Competência', academyRole: 'Função na Academia', refereeRole: 'Função de Árbitro', description: 'Descrição', testPart: 'Part. Teste', bugReports: 'Relatórios de Bug', suggestions: 'Sugestões', support: 'Suporte', refPerf: 'Desemp. Árbitro', qa: 'QA', discordPc: 'Discord PC', mgrOpinion: 'Opinião do Gerente', member: 'Membro', usersByGame: 'Usuários por Jogo', usersByRegion: 'Usuários por Região', topPerformers: 'Melhores Desempenhos', systemActivity: 'Atividade do Sistema', recentActivity: 'Atividade Recente', roleSimulation: 'Simulação de Função', profileSettings: 'Configurações de Perfil', email: 'E-mail', noUsersFound: 'Nenhum usuário encontrado para este jogo e região.', noAcademyFound: 'Nenhum membro da academia encontrado para este jogo e região.', noRefereesFound: 'Nenhum árbitro encontrado para este jogo e região.', notifications: 'Notificações', noNotifications: 'Nenhuma nova notificação', changeRoleDesc: 'Altere sua função atual para simular como o sistema aparece para diferentes usuários.', recentActionsDesc: 'Ações recentes realizadas no sistema.', userPerformanceUpdated: 'Desempenho do usuário atualizado', hoursAgo: 'horas atrás por Admin', adminUser: 'Usuário Admin', allGames: 'Todos os Jogos', allRegions: 'Todas as Regiões', editUser: 'Editar Usuário', copyToClipboard: 'Copiar para área de transferência',
      systemAccess: 'Criar Login no Sistema', yes: 'Sim', no: 'Não', resetPassword: 'Redefinir Senha', passwordResetSuccess: 'Solicitação de redefinição de senha enviada.', userLogs: 'Registros de Usuário', noLogs: 'Nenhum registro encontrado.', roleManagement: 'Gerenciamento de Funções', addNewRole: 'Adicionar Nova Função', roleName: 'Nome da Função', permissions: 'Permissões', pages: 'Páginas', deactivationReasonRequired: 'Introduza um motivo para desativar o utilizador.', addUser: 'Novo Usuário', userIdExists: 'Este ID de Membro ya está en uso.', inGameUsernameExists: 'Este Nome Tática no Jogo já está em uso.', systemUsernameExists: 'Este Nome de Usuário do Sistema já está em uso.', emailExists: 'Este endereço de E-mail já está em uso.', invalidEmailFormat: 'Por favor, insira um endereço de E-mail válido.', invalidInGameUsernameFormat: 'O Nome no Jogo deve ter de 3 a 12 caracteres e apenas pode conter letras, números e caracteres especiais permitidos: ! ^ / + ? = _ - $ # { } [ ] | ~ ` < > *', invalidSystemUsernameFormat: 'O Nome de Usuário do Sistema deve ter entre 4 a 10 caracteres e só pode conter letras do alfabeto inglês e números.', discordIdExists: 'Este Discord ID já está em uso.', invalidDiscordIdFormat: 'Discord ID deve ter pelo menos 17 dígitos.', discordIdRequired: 'Discord ID é necessário.',
      role_sysadmin: 'Administrador del Sistema', role_compmgr: 'Gerente da Empresa', role_compstaff: 'Equipe da Empresa', role_acadcap: 'Capitão da Academia', role_acadmem: 'Membro da Academia', role_fedaimem: 'Membro Fedai', role_headref: 'Árbitro Principal', role_ref: 'Árbitro', role_obs: 'Observador', role_discordmod: 'Moderador Discord', discordId: 'Discord ID', appTitle: 'MadByte Academia', footer_contact: 'Contato', discordTimeout: 'Tempo de espera do Discord', discordBan: 'Banimento do Discord', discordMessageDelete: 'Excluir mensagem do Discord',
      month_01: 'JANEIRO', month_02: 'FEVEREIRO', month_03: 'MARÇO', month_04: 'ABRIL', month_05: 'MAIO', month_06: 'JUNHO', month_07: 'JULHO', month_08: 'AGOSTO', month_09: 'SETEMBRO', month_10: 'OUTUBRO', month_11: 'NOVEMBRO', month_12: 'DEZEMBRO',
      loginDesc: 'Login do Painel de Gestão de Desempenho', usernameOrEmail: 'Usuário / E-mail', enterUsername: 'Digite o usuário ou e-mail', noAccountDesc: 'Se você não tem uma conta ou tem problemas de acesso', systemAdmin: 'Administrador do Sistema', contactWith: 'entre em contato com.',
    }
  },
  es: {
    translation: {
      dashboard: 'Panel', users: 'Usuarios', performance: 'Gestión del Rendimiento', academy: 'Miembros de la Academia', referees: 'Miembros Árbitros', reports: 'Informes', logs: 'Registros del Sistema', settings: 'Ajustes', search: 'Buscar...', language: 'Idioma', theme: 'Tema', logout: 'Cerrar sesión', totalUsers: 'Total de Usuarios', activeUsers: 'Usuarios Activos', totalReports: 'Total de Informes', avgPerformance: 'Rendimiento Medio', game: 'Juego', region: 'Región', status: 'Estado', role: 'Rol', actions: 'Acciones', edit: 'Editar', save: 'Guardar', cancel: 'Cancelar', add: 'Añadir', delete: 'Eliminar', active: 'Activo', passive: 'Pasivo', deactivationReason: 'Motivo de Desactivación', required: 'Requerido', participationTotal: 'Participación Total', overallPerformance: 'Rendimiento General', details: 'Detalles', notes: 'Notas',
      performanceManagement: 'Gestión del Rendimiento', performanceReports: 'Informes de Rendimiento',
      userId: 'ID de Miembro', inGameUsername: 'Nombre en el Juego', systemUsername: 'Nombre en el Sistema', fullName: 'Nombre Completo', roleCompetency: 'Rol / Competencia', academyRole: 'Rol de Academia', refereeRole: 'Rol de Árbitro', description: 'Descripción', testPart: 'Part. Prueba', bugReports: 'Informes de Error', suggestions: 'Sugerencias', support: 'Soporte', refPerf: 'Rend. Árbitro', qa: 'QA', discordPc: 'Discord PC', mgrOpinion: 'Opinión del Gerente', member: 'Miembro', usersByGame: 'Usuarios por Juego', usersByRegion: 'Usuarios por Región', topPerformers: 'Mejores Rendimientos', systemActivity: 'Actividad del Sistema', recentActivity: 'Actividad Reciente', roleSimulation: 'Simulación de Rol', profileSettings: 'Configuración de Perfil', email: 'Correo Electrónico', noUsersFound: 'No se encontraron usuarios para este juego y región.', noAcademyFound: 'No se encontraron miembros de la academia para este juego y región.', noRefereesFound: 'No se encontraron árbitros para este juego y región.', notifications: 'Notificaciones', noNotifications: 'No hay nuevas notificaciones', changeRoleDesc: 'Cambie su rol actual para simular cómo aparece el sistema para diferentes usuarios.', recentActionsDesc: 'Acciones recientes realizadas en el sistema.', userPerformanceUpdated: 'Rendimiento del usuario actualizado', hoursAgo: 'horas atrás por Admin', adminUser: 'Usuario Admin', allGames: 'Todos los Juegos', allRegions: 'Todas las Regiones', editUser: 'Editar Usuario', copyToClipboard: 'Copiar al portapapeles',
      systemAccess: 'Crear Inicio de Sesión', yes: 'Sí', no: 'No', resetPassword: 'Restablecer Contraseña', passwordResetSuccess: 'Solicitud de restablecimiento de contraseña enviada.', userLogs: 'Registros de Usuario', noLogs: 'No se encontraron registros.', roleManagement: 'Gestión de Roles', addNewRole: 'Añadir Nuevo Rol', roleName: 'Nombre del Rol', permissions: 'Permisos', pages: 'Páginas', deactivationReasonRequired: 'Por favor, introduzca un motivo para desactivar al usuario.', addUser: 'Nuevo Usuario', userIdExists: 'Este ID de Miembro ya está en uso.', inGameUsernameExists: 'Este Nombre en el Juego ya está en uso.', systemUsernameExists: 'Este Nombre de Usuario del Sistema ya está en uso.', emailExists: 'Este correo electrónico ya está en uso.', invalidEmailFormat: 'Por favor, introduzca una dirección de correo electrónico válida.', invalidInGameUsernameFormat: 'El Nombre en el Juego debe tener entre 3 y 12 caracteres y solo puede contener letras, números y caracteres especiales permitidos: ! ^ / + ? = _ - $ # { } [ ] | ~ ` < > *', invalidSystemUsernameFormat: 'El Nombre de Usuario del Sistema debe tener entre 4 y 10 caracteres y solo puede contener letras y números en inglés.', discordIdExists: 'Este Discord ID ya está en uso.', invalidDiscordIdFormat: 'Discord ID debe tener al menos 17 dígitos.', discordIdRequired: 'Discord ID es requerido.',
      role_sysadmin: 'Administrador del Sistema', role_compmgr: 'Gerente de la Empresa', role_compstaff: 'Personal de la Empresa', role_acadcap: 'Capitán de la Academia', role_acadmem: 'Miembro de la Academia', role_fedaimem: 'Miembro Fedai', role_headref: 'Árbitro Principal', role_ref: 'Árbitro', role_obs: 'Observador', role_discordmod: 'Moderador Discord', discordId: 'Discord ID', appTitle: 'MadByte Academia', footer_contact: 'Contacto', discordTimeout: 'Tiempo de espera de Discord', discordBan: 'Ban de Discord', discordMessageDelete: 'Eliminar mensaje de Discord',
      month_01: 'ENERO', month_02: 'FEBRERO', month_03: 'MARZO', month_04: 'ABRIL', month_05: 'MAIO', month_06: 'JUNHO', month_07: 'JULHO', month_08: 'AGOSTO', month_09: 'SEPTIEMBRE', month_10: 'OCTUBRE', month_11: 'NOVIEMBRE', month_12: 'DICIEMBRE',
      loginDesc: 'Inicio de Sesión del Panel de Gestión del Rendimiento', usernameOrEmail: 'Usuario / Correo Electrónico', enterUsername: 'Ingrese usuario o correo electrónico', noAccountDesc: 'Si no tiene una cuenta o tiene problemas de acceso', systemAdmin: 'Administrador del Sistema', contactWith: 'póngase en contacto con.',
    }
  },
  ru: {
    translation: {
      dashboard: 'Панель', users: 'Пользователи', performance: 'Управление Производительностью', academy: 'Члены Академии', referees: 'Члены Судьи', reports: 'Отчеты', logs: 'Системные Журналы', settings: 'Настройки', search: 'Поиск...', language: 'Язык', theme: 'Тема', logout: 'Выйти', totalUsers: 'Всего Пользователей', activeUsers: 'Активные Пользователи', totalReports: 'Всего Отчетов', avgPerformance: 'Ср. Производительность', game: 'Игра', region: 'Регион', status: 'Статус', role: 'Роль', actions: 'Действия', edit: 'Редактировать', save: 'Сохранить', cancel: 'Отмена', add: 'Добавить', delete: 'Удалить', active: 'Активный', passive: 'Пассивный', deactivationReason: 'Причина Деактивации', required: 'Обязательно', participationTotal: 'Общее Участие', overallPerformance: 'Общая Производительность', details: 'Детали', notes: 'Заметки',
      performanceManagement: 'Управление Производительностью', performanceReports: 'Отчеты о Производительности',
      userId: 'ID Участника', inGameUsername: 'Имя в Игре', systemUsername: 'Имя в Системе', fullName: 'Полное Имя', roleCompetency: 'Роль / Компетенция', academyRole: 'Роль в Академии', refereeRole: 'Роль Судьи', description: 'Описание', testPart: 'Участ. в Тестах', bugReports: 'Отчеты об Ошибках', suggestions: 'Предложения', support: 'Поддержка', refPerf: 'Произв. Судьи', qa: 'QA', discordPc: 'Discord PC', mgrOpinion: 'Мнение Менеджера', member: 'Участник', usersByGame: 'Пользователи по Играм', usersByRegion: 'Пользователи по Регионам', topPerformers: 'Лучшие Исполнители', systemActivity: 'Системная Активность', recentActivity: 'Недавняя Активность', roleSimulation: 'Симуляция Роли', profileSettings: 'Настройки Профиля', email: 'Электронная Почта', noUsersFound: 'Пользователи не найдены для этой игры и региона.', noAcademyFound: 'Члены академии не найдены для этой игры и региона.', noRefereesFound: 'Судьи не найдены для этой игры и региона.', notifications: 'Уведомления', noNotifications: 'Нет новых уведомлений', changeRoleDesc: 'Измените свою текущую роль, чтобы смоделировать, как система выглядит для разных пользователей.', recentActionsDesc: 'Недавние действия, выполненные в системе.', userPerformanceUpdated: 'Производительность пользователя обновлена', hoursAgo: 'часов назад от Admin', adminUser: 'Пользователь Admin', allGames: 'Все Игры', allRegions: 'Все Регионы', editUser: 'Редактировать Пользователя', copyToClipboard: 'Скопировать в буфер обмена',
      systemAccess: 'Создать Системный Вход', yes: 'Да', no: 'Нет', resetPassword: 'Сбросить Пароль', passwordResetSuccess: 'Запрос на сброс пароля отправлен.', userLogs: 'Журналы Пользователя', noLogs: 'Журналы не найдены.', roleManagement: 'Управление Ролями', addNewRole: 'Добавить Новую Роль', roleName: 'Имя Роли', permissions: 'Разрешения', pages: 'Страницы', deactivationReasonRequired: 'Пожалуйста, введите причину для деактивации пользователя.', addUser: 'Новый Пользователь', userIdExists: 'Этот ID Участника уже используется.', inGameUsernameExists: 'Это Имя в Игре уже используется.', systemUsernameExists: 'Это Имя в Системе уже используется.', emailExists: 'Этот адрес Электронной Почты уже используется.', invalidEmailFormat: 'Пожалуйста, введите действительный адрес электронной почты.', invalidInGameUsernameFormat: 'Имя в Игре должно состоять из 3-12 символов и может содержать только буквы, цифры и разрешенные специальные символы: ! ^ / + ? = _ - $ # { } [ ] | ~ ` < > *', invalidSystemUsernameFormat: 'Имя в Системе должно состоять из 4-10 символов и может содержать только английские буквы и цифры.', discordIdExists: 'Этот Discord ID уже используется.', invalidDiscordIdFormat: 'Discord ID должен содержать не менее 17 цифр.', discordIdRequired: 'Требуется Discord ID.',
      role_sysadmin: 'Системный Администратор', role_compmgr: 'Менеджер Компании', role_compstaff: 'Сотрудник Компании', role_acadcap: 'Капитан Академии', role_acadmem: 'Член Академии', role_fedaimem: 'Член Fedai', role_headref: 'Главный Судья', role_ref: 'Судья', role_obs: 'Наблюдатель', role_discordmod: 'Модератор Discord', discordId: 'Discord ID', appTitle: 'MadByte Академия', footer_contact: 'Контакты', discordTimeout: 'Тайм-аут Discord', discordBan: 'Бан в Discord', discordMessageDelete: 'Удаление сообщения в Discord',
      month_01: 'ЯНВАРЬ', month_02: 'ФЕВРАЛЬ', month_03: 'МАРТ', month_04: 'АПРЕЛЬ', month_05: 'МАЙ', month_06: 'ИЮНЬ', month_07: 'ИЮЛЬ', month_08: 'АВГУСТ', month_09: 'СЕНТЯБРЬ', month_10: 'ОКТЯБРЬ', month_11: 'НОЯБРЬ', month_12: 'ДЕКАБРЬ',
      loginDesc: 'Вход в панель управления производительностью', usernameOrEmail: 'Имя пользователя / Эл. почта', enterUsername: 'Введите имя пользователя или эл. почту', noAccountDesc: 'Если у вас нет учетной записи или возникли проблемы с доступом', systemAdmin: 'Системный администратор', contactWith: 'свяжитесь с.',
    }
  },
  ar: {
    translation: {
      dashboard: 'لوحة القيادة', users: 'المستخدمين', performance: 'إدارة الأداء', academy: 'أعضاء الأكاديمية', referees: 'أعضاء الحكام', reports: 'التقارير', logs: 'سجلات النظام', settings: 'الإعدادات', search: 'بحث...', language: 'اللغة', theme: 'سمة', logout: 'تسجيل خروج', totalUsers: 'إجمالي المستخدمين', activeUsers: 'المستخدمين النشطين', totalReports: 'إجمالي التقارير', avgPerformance: 'متوسط الأداء', game: 'لعبة', region: 'منطقة', status: 'حالة', role: 'دور', actions: 'أفعال', edit: 'تعديل', save: 'حفظ', cancel: 'إلغاء', add: 'إضافة', delete: 'حذف', active: 'نشط', passive: 'سلبي', deactivationReason: 'سبب التعطيل', required: 'مطلوب', participationTotal: 'إجمالي المشاركة', overallPerformance: 'الأداء العام', details: 'تفاصيل', notes: 'ملاحظات',
      performanceManagement: 'إدارة الأداء', performanceReports: 'تقارير الأداء',
      userId: 'معرف العضو', inGameUsername: 'اسم المستخدم في اللعبة', systemUsername: 'اسم المستخدم في النظام', fullName: 'الاسم الكامل', roleCompetency: 'الدور / الكفاءة', academyRole: 'دور الأكاديمية', refereeRole: 'دور الحكم', description: 'الوصف', testPart: 'مشاركة الاختبار', bugReports: 'تقارير الأخطاء', suggestions: 'اقتراحات', support: 'دعم', refPerf: 'أداء الحكم', qa: 'ضمان الجودة', discordPc: 'ديسكورد كمبيوتر', mgrOpinion: 'رأي المدير', member: 'عضو', usersByGame: 'المستخدمين حسب اللعبة', usersByRegion: 'المستخدمين حسب المنطقة', topPerformers: 'أفضل الأداء', systemActivity: 'نشاط النظام', recentActivity: 'النشاط الأخير', roleSimulation: 'محاكاة الدور', profileSettings: 'إعدادات الملف الشخصي', email: 'البريد الإلكتروني', noUsersFound: 'لم يتم العثور على مستخدمين لهذه اللعبة والمنطقة.', noAcademyFound: 'لم يتم العثور على أعضاء أكاديمية لهذه اللعبة والمنطقة.', noRefereesFound: 'لم يتم العثور على حكام لهذه اللعبة والمنطقة.', notifications: 'إشعارات', noNotifications: 'لا توجد إشعارات جديدة', changeRoleDesc: 'قم بتغيير دورك الحالي لمحاكاة كيفية ظهور النظام للمستخدمين المختلفين.', recentActionsDesc: 'الإجراءات الأخيرة التي تم تنفيذها في النظام.', userPerformanceUpdated: 'تم تحديث أداء المستخدم', hoursAgo: 'ساعات مضت بواسطة المشرف', adminUser: 'مستخدم مشرف', allGames: 'كل الألعاب', allRegions: 'كل المناطق', editUser: 'تعديل المستخدم', copyToClipboard: 'نسخ إلى الحافظة',
      systemAccess: 'إنشاء تسجيل الدخول', yes: 'نعم', no: 'لا', resetPassword: 'إعادة تعيين كلمة المرور', passwordResetSuccess: 'تم إرسال طلب إعادة تعيين كلمة المرور.', userLogs: 'سجلات المستخدم', noLogs: 'لم يتم العثور على سجلات.', roleManagement: 'إدارة الأدوار', addNewRole: 'إضافة دور جديد', roleName: 'اسم الدور', permissions: 'أذونات', pages: 'صفحات', deactivationReasonRequired: 'الرجاء إدخال سبب لتعطيل المستخدم.', addUser: 'مستخدم جديد', userIdExists: 'معرف العضو هذا قيد الاستخدام بالفعل.', inGameUsernameExists: 'اسم المستخدم في اللعبة هذا قيد الاستخدام بالفعل.', systemUsernameExists: 'اسم المستخدم في النظام هذا قيد الاستخدام بالفعل.', emailExists: 'عنوان البريد الإلكتروني هذا قيد الاستخدام بالفعل.', invalidEmailFormat: 'يرجى إدخال عنوان بريد إلكتروني صالح.', invalidInGameUsernameFormat: 'يجب أن يتكون اسم المستخدم في اللعبة من 3 إلى 12 حرفًا ويمكن أن يحتوي فقط على أحرف وأرقام وأحرف خاصة مسموح بها: ! ^ / + ? = _ - $ # { } [ ] | ~ ` < > *', invalidSystemUsernameFormat: 'يجب أن يتكون اسم النظام الخاص بالمستخدم من 4 إلى 10 أحرف وأن يحتوي فقط على الأحرف والأرقام الإنجليزية.', discordIdExists: 'معرف Discord هذا قيد الاستخدام بالفعل.', invalidDiscordIdFormat: 'يجب أن يتكون معرف Discord من 17 رقمًا على الأقل.', discordIdRequired: 'مطلوب Discord ID.',
      role_sysadmin: 'مسؤول النظام', role_compmgr: 'مدير الشركة', role_compstaff: 'موظف الشركة', role_acadcap: 'كابتن الأكاديمية', role_acadmem: 'عضو الأكاديمية', role_fedaimem: 'عضو فدائي', role_headref: 'رئيس الحكام', role_ref: 'حكم', role_obs: 'مراقب', role_discordmod: 'مشرف ديسكورد', discordId: 'Discord ID', appTitle: 'أكاديمية مادبايت', footer_contact: 'اتصال', discordTimeout: 'مهلة Discord', discordBan: 'حظر Discord', discordMessageDelete: 'حذف رسالة Discord',
      month_01: 'يناير', month_02: 'فبراير', month_03: 'مارس', month_04: 'أبريل', month_05: 'مايو', month_06: 'يونيو', month_07: 'يوليو', month_08: 'أغسطس', month_09: 'سبتمبر', month_10: 'أكتوبر', month_11: 'نوفمبر', month_12: 'ديسمبر',
      loginDesc: 'تسجيل الدخول إلى لوحة إدارة الأداء', usernameOrEmail: 'اسم المستخدم / البريد الإلكتروني', enterUsername: 'أدخل اسم المستخدم أو البريد الإلكتروني', noAccountDesc: 'إذا لم يكن لديك حساب أو واجهت مشاكل في الوصول', systemAdmin: 'مسؤول النظام', contactWith: 'تواصل مع.',
    }
  }
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'tr',
    detection: {
      order: ['localStorage', 'navigator'],
      caches: ['localStorage'],
    },
    interpolation: {
      escapeValue: false
    }
  });

export default i18n;
